/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/Users/dxy/Downloads/dxy-gzh/Front-end-Interview/node_modules/@vuepress/core/lib/client/root-mixins/updateMeta.js"
import m1 from "/Users/dxy/Downloads/dxy-gzh/Front-end-Interview/node_modules/@vuepress/plugin-active-header-links/clientRootMixin.js"
import m2 from "/Users/dxy/Downloads/dxy-gzh/Front-end-Interview/node_modules/@vuepress/plugin-nprogress/clientRootMixin.js"
import m3 from "/Users/dxy/Downloads/dxy-gzh/Front-end-Interview/node_modules/_@vuepress_plugin-medium-zoom@1.0.1@@vuepress/plugin-medium-zoom/clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]