/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/dxy/Documents/dxy-gzh/front-end-interview/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7364f2b6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7364f2b6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-38038a4a",
    path: "/guide/book.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38038a4a").then(next)
    },
  },
  {
    name: "v-a6b0f6ea",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6b0f6ea").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-5db7e350",
    path: "/guide/abstract.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5db7e350").then(next)
    },
  },
  {
    name: "v-08fc6914",
    path: "/guide/browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08fc6914").then(next)
    },
  },
  {
    name: "v-c64d1774",
    path: "/guide/common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c64d1774").then(next)
    },
  },
  {
    name: "v-909d7754",
    path: "/guide/component.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-909d7754").then(next)
    },
  },
  {
    name: "v-9ec1af54",
    path: "/guide/componentCli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9ec1af54").then(next)
    },
  },
  {
    name: "v-26a54b74",
    path: "/guide/cssBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26a54b74").then(next)
    },
  },
  {
    name: "v-d47e3e54",
    path: "/guide/deepclone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d47e3e54").then(next)
    },
  },
  {
    name: "v-1d743fcc",
    path: "/guide/designPatterns.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d743fcc").then(next)
    },
  },
  {
    name: "v-7b8fa194",
    path: "/guide/devsProxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b8fa194").then(next)
    },
  },
  {
    name: "v-d62d5894",
    path: "/guide/dom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d62d5894").then(next)
    },
  },
  {
    name: "v-69018a14",
    path: "/guide/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69018a14").then(next)
    },
  },
  {
    name: "v-0f593414",
    path: "/guide/eventLoop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f593414").then(next)
    },
  },
  {
    name: "v-26cb8136",
    path: "/guide/fiber.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26cb8136").then(next)
    },
  },
  {
    name: "v-1aa489f6",
    path: "/guide/framework.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1aa489f6").then(next)
    },
  },
  {
    name: "v-0527eb44",
    path: "/guide/hoisting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0527eb44").then(next)
    },
  },
  {
    name: "v-7636ce16",
    path: "/guide/htmlBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7636ce16").then(next)
    },
  },
  {
    name: "v-2610bfe8",
    path: "/guide/http.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2610bfe8").then(next)
    },
  },
  {
    name: "v-0dcf6a96",
    path: "/guide/httpWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0dcf6a96").then(next)
    },
  },
  {
    name: "v-c6715f14",
    path: "/guide/immutable.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c6715f14").then(next)
    },
  },
  {
    name: "v-6faacdd6",
    path: "/guide/jsBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6faacdd6").then(next)
    },
  },
  {
    name: "v-95dc5814",
    path: "/guide/jsWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95dc5814").then(next)
    },
  },
  {
    name: "v-1b672d60",
    path: "/guide/load.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b672d60").then(next)
    },
  },
  {
    name: "v-2d28b59a",
    path: "/guide/memory.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d28b59a").then(next)
    },
  },
  {
    name: "v-13d67076",
    path: "/guide/preface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13d67076").then(next)
    },
  },
  {
    name: "v-561489d6",
    path: "/guide/mechanism.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-561489d6").then(next)
    },
  },
  {
    name: "v-571d1f56",
    path: "/guide/project.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-571d1f56").then(next)
    },
  },
  {
    name: "v-7f195d96",
    path: "/guide/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f195d96").then(next)
    },
  },
  {
    name: "v-612b2876",
    path: "/guide/reactHook.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-612b2876").then(next)
    },
  },
  {
    name: "v-1f0a8450",
    path: "/guide/reactivity.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f0a8450").then(next)
    },
  },
  {
    name: "v-07bf9b94",
    path: "/guide/redux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07bf9b94").then(next)
    },
  },
  {
    name: "v-6598957e",
    path: "/guide/setState.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6598957e").then(next)
    },
  },
  {
    name: "v-176f5554",
    path: "/guide/tcp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-176f5554").then(next)
    },
  },
  {
    name: "v-14677eb0",
    path: "/guide/type.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14677eb0").then(next)
    },
  },
  {
    name: "v-b3cc06a4",
    path: "/guide/virtualDom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3cc06a4").then(next)
    },
  },
  {
    name: "v-14935594",
    path: "/guide/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14935594").then(next)
    },
  },
  {
    name: "v-87310654",
    path: "/guide/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87310654").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]