/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.svg",
        "actionText": "开始 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "追求重点和难点,剔除陈旧的知识。"
          },
          {
            "title": "清晰易懂",
            "details": "将复杂的问题一一拆解。"
          },
          {
            "title": "紧跟热点",
            "details": "当下热点技术一网打尽。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2019-present xiaomuzhu"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-77cab7d0",
      "path": "/"
    },
    {
      "title": "书籍/课程推荐",
      "frontmatter": {},
      "regularPath": "/guide/book.html",
      "relativePath": "guide/book.md",
      "key": "v-281299f7",
      "path": "/guide/book.html",
      "headers": [
        {
          "level": 2,
          "title": "书单",
          "slug": "书单"
        },
        {
          "level": 3,
          "title": "JavaScript",
          "slug": "javascript"
        },
        {
          "level": 3,
          "title": "CSS:",
          "slug": "css"
        },
        {
          "level": 3,
          "title": "算法：",
          "slug": "算法："
        },
        {
          "level": 3,
          "title": "安全：",
          "slug": "安全："
        },
        {
          "level": 3,
          "title": "canvas：",
          "slug": "canvas："
        },
        {
          "level": 3,
          "title": "Node",
          "slug": "node"
        },
        {
          "level": 3,
          "title": "网络",
          "slug": "网络"
        },
        {
          "level": 2,
          "title": "关于知识付费",
          "slug": "关于知识付费"
        },
        {
          "level": 3,
          "title": "知乎live",
          "slug": "知乎live"
        },
        {
          "level": 3,
          "title": "掘金册子",
          "slug": "掘金册子"
        },
        {
          "level": 3,
          "title": "极客时间",
          "slug": "极客时间"
        },
        {
          "level": 3,
          "title": "慕课网",
          "slug": "慕课网"
        }
      ]
    },
    {
      "title": "指南使用手册",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-5b8d0d7e",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "项目结构概览",
          "slug": "项目结构概览"
        },
        {
          "level": 2,
          "title": "模块概览",
          "slug": "模块概览"
        },
        {
          "level": 3,
          "title": "前端基础",
          "slug": "前端基础"
        },
        {
          "level": 3,
          "title": "框架解读",
          "slug": "框架解读"
        },
        {
          "level": 3,
          "title": "工程化",
          "slug": "工程化"
        },
        {
          "level": 3,
          "title": "Typescript",
          "slug": "typescript"
        },
        {
          "level": 3,
          "title": "性能优化",
          "slug": "性能优化"
        },
        {
          "level": 3,
          "title": "计算机基础",
          "slug": "计算机基础"
        },
        {
          "level": 3,
          "title": "细分领域",
          "slug": "细分领域"
        }
      ]
    },
    {
      "title": "浏览器与新技术",
      "frontmatter": {},
      "regularPath": "/guide/browser.html",
      "relativePath": "guide/browser.md",
      "key": "v-bd40b53a",
      "path": "/guide/browser.html",
      "headers": [
        {
          "level": 2,
          "title": "常见的浏览器内核有哪些?",
          "slug": "常见的浏览器内核有哪些"
        },
        {
          "level": 2,
          "title": "浏览器的主要组成部分是什么？",
          "slug": "浏览器的主要组成部分是什么？"
        },
        {
          "level": 2,
          "title": "浏览器是如何渲染UI的？",
          "slug": "浏览器是如何渲染ui的？"
        },
        {
          "level": 2,
          "title": "浏览器如何解析css选择器？",
          "slug": "浏览器如何解析css选择器？"
        },
        {
          "level": 2,
          "title": "DOM Tree是如何构建的？",
          "slug": "dom-tree是如何构建的？"
        },
        {
          "level": 2,
          "title": "浏览器重绘与重排的区别？",
          "slug": "浏览器重绘与重排的区别？"
        },
        {
          "level": 2,
          "title": "如何触发重排和重绘？",
          "slug": "如何触发重排和重绘？"
        },
        {
          "level": 2,
          "title": "如何避免重绘或者重排？",
          "slug": "如何避免重绘或者重排？"
        },
        {
          "level": 3,
          "title": "集中改变样式",
          "slug": "集中改变样式"
        },
        {
          "level": 3,
          "title": "使用DocumentFragment",
          "slug": "使用documentfragment"
        },
        {
          "level": 3,
          "title": "提升为合成层",
          "slug": "提升为合成层"
        },
        {
          "level": 2,
          "title": "前端如何实现即时通讯？",
          "slug": "前端如何实现即时通讯？"
        },
        {
          "level": 3,
          "title": "短轮询",
          "slug": "短轮询"
        },
        {
          "level": 3,
          "title": "comet",
          "slug": "comet"
        },
        {
          "level": 3,
          "title": "SSE",
          "slug": "sse"
        },
        {
          "level": 3,
          "title": "Websocket",
          "slug": "websocket"
        },
        {
          "level": 3,
          "title": "Web Worker",
          "slug": "web-worker"
        },
        {
          "level": 3,
          "title": "Service workers",
          "slug": "service-workers"
        }
      ]
    },
    {
      "title": "CSS基础",
      "frontmatter": {},
      "regularPath": "/guide/cssBasic.html",
      "relativePath": "guide/cssBasic.md",
      "key": "v-db07261a",
      "path": "/guide/cssBasic.html",
      "headers": [
        {
          "level": 2,
          "title": "CSS选择器的优先级是怎样的？✨",
          "slug": "css选择器的优先级是怎样的？✨"
        },
        {
          "level": 2,
          "title": "link和@import的区别？",
          "slug": "link和-import的区别？"
        },
        {
          "level": 2,
          "title": "有哪些方式（CSS）可以隐藏页面元素？",
          "slug": "有哪些方式（css）可以隐藏页面元素？"
        },
        {
          "level": 2,
          "title": "em\\px\\rem区别？",
          "slug": "em-px-rem区别？"
        },
        {
          "level": 2,
          "title": "块级元素水平居中的方法？",
          "slug": "块级元素水平居中的方法？"
        },
        {
          "level": 2,
          "title": "CSS有几种定位方式？",
          "slug": "css有几种定位方式？"
        },
        {
          "level": 2,
          "title": "如何理解z-index？✨",
          "slug": "如何理解z-index？✨"
        },
        {
          "level": 2,
          "title": "如何理解层叠上下文？✨",
          "slug": "如何理解层叠上下文？✨"
        },
        {
          "level": 3,
          "title": "是什么？",
          "slug": "是什么？"
        },
        {
          "level": 3,
          "title": "如何产生？",
          "slug": "如何产生？"
        },
        {
          "level": 2,
          "title": "清除浮动有哪些方法？",
          "slug": "清除浮动有哪些方法？"
        },
        {
          "level": 2,
          "title": "你对css sprites的理解，好处是什么？",
          "slug": "你对css-sprites的理解，好处是什么？"
        },
        {
          "level": 3,
          "title": "是什么 ？",
          "slug": "是什么-？"
        },
        {
          "level": 3,
          "title": "如何操作？",
          "slug": "如何操作？"
        },
        {
          "level": 3,
          "title": "好处：",
          "slug": "好处："
        },
        {
          "level": 3,
          "title": "不足：",
          "slug": "不足："
        },
        {
          "level": 2,
          "title": "你对媒体查询的理解？",
          "slug": "你对媒体查询的理解？"
        },
        {
          "level": 3,
          "title": "是什么",
          "slug": "是什么"
        },
        {
          "level": 3,
          "title": "如何使用？",
          "slug": "如何使用？"
        },
        {
          "level": 2,
          "title": "你对盒模型的理解？ ✨",
          "slug": "你对盒模型的理解？-✨"
        },
        {
          "level": 3,
          "title": "是什么？",
          "slug": "是什么？-2"
        },
        {
          "level": 2,
          "title": "标准盒模型和怪异盒模型有什么区别？✨",
          "slug": "标准盒模型和怪异盒模型有什么区别？✨"
        },
        {
          "level": 2,
          "title": "谈谈对BFC(Block Formatting Context)的理解？ ✨",
          "slug": "谈谈对bfc-block-formatting-context-的理解？-✨"
        },
        {
          "level": 3,
          "title": "是什么？",
          "slug": "是什么？-3"
        },
        {
          "level": 3,
          "title": "如何形成？",
          "slug": "如何形成？"
        },
        {
          "level": 3,
          "title": "作用是什么？",
          "slug": "作用是什么？"
        },
        {
          "level": 2,
          "title": "为什么有时候人们用translate来改变位置而不是定位？",
          "slug": "为什么有时候人们用translate来改变位置而不是定位？"
        },
        {
          "level": 2,
          "title": "伪类和伪元素的区别是什么？",
          "slug": "伪类和伪元素的区别是什么？"
        },
        {
          "level": 3,
          "title": "是什么？",
          "slug": "是什么？-4"
        },
        {
          "level": 3,
          "title": "区别",
          "slug": "区别"
        },
        {
          "level": 2,
          "title": "你对flex的理解？✨",
          "slug": "你对flex的理解？✨"
        },
        {
          "level": 2,
          "title": "关于CSS的动画与过渡问题",
          "slug": "关于css的动画与过渡问题"
        }
      ]
    },
    {
      "title": "实现深克隆",
      "frontmatter": {},
      "regularPath": "/guide/deepclone.html",
      "relativePath": "guide/deepclone.md",
      "key": "v-0415fc43",
      "path": "/guide/deepclone.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "浅克隆",
          "slug": "浅克隆"
        },
        {
          "level": 2,
          "title": "深克隆",
          "slug": "深克隆"
        },
        {
          "level": 3,
          "title": "JSON.parse方法",
          "slug": "json-parse方法"
        },
        {
          "level": 3,
          "title": "2.2 构造一个深克隆函数",
          "slug": "_2-2-构造一个深克隆函数"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "DOM",
      "frontmatter": {},
      "regularPath": "/guide/dom.html",
      "relativePath": "guide/dom.md",
      "key": "v-1ee26aa3",
      "path": "/guide/dom.html",
      "headers": [
        {
          "level": 2,
          "title": "DOM的事件模型是什么？",
          "slug": "dom的事件模型是什么？"
        },
        {
          "level": 2,
          "title": "DOM的事件流是什么？",
          "slug": "dom的事件流是什么？"
        },
        {
          "level": 3,
          "title": "事件冒泡",
          "slug": "事件冒泡"
        },
        {
          "level": 3,
          "title": "事件捕获",
          "slug": "事件捕获"
        },
        {
          "level": 3,
          "title": "事件流",
          "slug": "事件流"
        },
        {
          "level": 2,
          "title": "什么是事件委托?",
          "slug": "什么是事件委托"
        }
      ]
    },
    {
      "title": "如何实现一个Event",
      "frontmatter": {},
      "regularPath": "/guide/event.html",
      "relativePath": "guide/event.md",
      "key": "v-17edd93a",
      "path": "/guide/event.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "基本构造",
          "slug": "基本构造"
        },
        {
          "level": 3,
          "title": "初始化class",
          "slug": "初始化class"
        },
        {
          "level": 3,
          "title": "监听与触发",
          "slug": "监听与触发"
        },
        {
          "level": 2,
          "title": "升级改造",
          "slug": "升级改造"
        },
        {
          "level": 3,
          "title": "监听/触发器升级",
          "slug": "监听-触发器升级"
        },
        {
          "level": 3,
          "title": "移除监听",
          "slug": "移除监听"
        },
        {
          "level": 3,
          "title": "发现问题",
          "slug": "发现问题"
        }
      ]
    },
    {
      "title": "Event Loop详解",
      "frontmatter": {},
      "regularPath": "/guide/eventLoop.html",
      "relativePath": "guide/eventLoop.md",
      "key": "v-66a88163",
      "path": "/guide/eventLoop.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "为啥要弄懂Event Loop",
          "slug": "为啥要弄懂event-loop"
        },
        {
          "level": 2,
          "title": "栈、队列的基本概念",
          "slug": "栈、队列的基本概念"
        },
        {
          "level": 3,
          "title": "栈（Stack）",
          "slug": "栈（stack）"
        },
        {
          "level": 3,
          "title": "队列（Queue）",
          "slug": "队列（queue）"
        },
        {
          "level": 2,
          "title": "Event Loop",
          "slug": "event-loop"
        },
        {
          "level": 3,
          "title": "MacroTask（宏任务）",
          "slug": "macrotask（宏任务）"
        },
        {
          "level": 3,
          "title": "MicroTask（微任务）",
          "slug": "microtask（微任务）"
        },
        {
          "level": 2,
          "title": "浏览器中的Event Loop",
          "slug": "浏览器中的event-loop"
        },
        {
          "level": 3,
          "title": "JS调用栈",
          "slug": "js调用栈"
        },
        {
          "level": 3,
          "title": "同步任务和异步任务",
          "slug": "同步任务和异步任务"
        },
        {
          "level": 3,
          "title": "事件循环的进程模型",
          "slug": "事件循环的进程模型"
        },
        {
          "level": 3,
          "title": "执行进入microtask检查点时，用户代理会执行以下步骤：",
          "slug": "执行进入microtask检查点时，用户代理会执行以下步骤："
        },
        {
          "level": 2,
          "title": "举个例子",
          "slug": "举个例子"
        },
        {
          "level": 3,
          "title": "第一次执行：",
          "slug": "第一次执行："
        },
        {
          "level": 3,
          "title": "第二次执行：",
          "slug": "第二次执行："
        },
        {
          "level": 3,
          "title": "第三次执行：",
          "slug": "第三次执行："
        },
        {
          "level": 3,
          "title": "第四次执行：",
          "slug": "第四次执行："
        },
        {
          "level": 2,
          "title": "再举个例子",
          "slug": "再举个例子"
        },
        {
          "level": 3,
          "title": "关于73以下版本和73版本的区别",
          "slug": "关于73以下版本和73版本的区别"
        },
        {
          "level": 3,
          "title": "在老版本中",
          "slug": "在老版本中"
        },
        {
          "level": 3,
          "title": "引用贺老师知乎上的一个例子",
          "slug": "引用贺老师知乎上的一个例子"
        },
        {
          "level": 3,
          "title": "谷歌（金丝雀）73版本中",
          "slug": "谷歌（金丝雀）73版本中"
        },
        {
          "level": 3,
          "title": "详细过程：",
          "slug": "详细过程："
        },
        {
          "level": 2,
          "title": "NodeJS的Event Loop",
          "slug": "nodejs的event-loop"
        },
        {
          "level": 3,
          "title": "Node的Event loop一共分为6个阶段，每个细节具体如下：",
          "slug": "node的event-loop一共分为6个阶段，每个细节具体如下："
        },
        {
          "level": 3,
          "title": "timers",
          "slug": "timers"
        },
        {
          "level": 3,
          "title": "pending callbacks",
          "slug": "pending-callbacks"
        },
        {
          "level": 3,
          "title": "poll",
          "slug": "poll"
        },
        {
          "level": 3,
          "title": "check",
          "slug": "check"
        },
        {
          "level": 2,
          "title": "setImmediate() 的setTimeout()的区别",
          "slug": "setimmediate-的settimeout-的区别"
        },
        {
          "level": 3,
          "title": "举个例子",
          "slug": "举个例子-2"
        },
        {
          "level": 2,
          "title": "Process.nextTick()",
          "slug": "process-nexttick"
        },
        {
          "level": 3,
          "title": "例子",
          "slug": "例子"
        }
      ]
    },
    {
      "title": "JavaScript的『预解释』与『变量提升』",
      "frontmatter": {},
      "regularPath": "/guide/hoisting.html",
      "relativePath": "guide/hoisting.md",
      "key": "v-b989c5ea",
      "path": "/guide/hoisting.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "从一个实例开始",
          "slug": "从一个实例开始"
        },
        {
          "level": 2,
          "title": "avaScript预解释",
          "slug": "avascript预解释"
        },
        {
          "level": 2,
          "title": "JavaScript执行环境",
          "slug": "javascript执行环境"
        },
        {
          "level": 2,
          "title": "变量提升",
          "slug": "变量提升"
        },
        {
          "level": 2,
          "title": "函数声明与函数表达式",
          "slug": "函数声明与函数表达式"
        },
        {
          "level": 2,
          "title": "冲突处理",
          "slug": "冲突处理"
        },
        {
          "level": 2,
          "title": "ES6中的let",
          "slug": "es6中的let"
        }
      ]
    },
    {
      "title": "HTML基础",
      "frontmatter": {},
      "regularPath": "/guide/htmlBasic.html",
      "relativePath": "guide/htmlBasic.md",
      "key": "v-36e82cfa",
      "path": "/guide/htmlBasic.html",
      "headers": [
        {
          "level": 2,
          "title": "doctype(文档类型) 的作用是什么？✨",
          "slug": "doctype-文档类型-的作用是什么？✨"
        },
        {
          "level": 2,
          "title": "这三种模式的区别是什么？(接上一问追问)",
          "slug": "这三种模式的区别是什么？-接上一问追问"
        },
        {
          "level": 2,
          "title": "HTML、XML 和 XHTML 有什么区别？",
          "slug": "html、xml-和-xhtml-有什么区别？"
        },
        {
          "level": 2,
          "title": "什么是data-属性？",
          "slug": "什么是data-属性？"
        },
        {
          "level": 2,
          "title": "你对HTML语义化的理解？✨",
          "slug": "你对html语义化的理解？✨"
        },
        {
          "level": 2,
          "title": "HTML5与HTML4的不同之处",
          "slug": "html5与html4的不同之处"
        },
        {
          "level": 2,
          "title": "有哪些常用的meta标签？",
          "slug": "有哪些常用的meta标签？"
        },
        {
          "level": 2,
          "title": "src和href的区别？",
          "slug": "src和href的区别？"
        },
        {
          "level": 2,
          "title": "知道img的srcset的作用是什么？（追问）",
          "slug": "知道img的srcset的作用是什么？（追问）"
        },
        {
          "level": 2,
          "title": "还有哪一个标签能起到跟srcset相似作用？（追问）",
          "slug": "还有哪一个标签能起到跟srcset相似作用？（追问）"
        },
        {
          "level": 2,
          "title": "script标签中defer和async的区别？✨",
          "slug": "script标签中defer和async的区别？✨"
        },
        {
          "level": 2,
          "title": "有几种前端储存的方式？✨",
          "slug": "有几种前端储存的方式？✨"
        },
        {
          "level": 2,
          "title": "这些方式的区别是什么？（追问）✨",
          "slug": "这些方式的区别是什么？（追问）✨"
        }
      ]
    },
    {
      "title": "HTTP协议",
      "frontmatter": {},
      "regularPath": "/guide/http.html",
      "relativePath": "guide/http.md",
      "key": "v-45f2a08e",
      "path": "/guide/http.html",
      "headers": [
        {
          "level": 2,
          "title": "HTTP有哪些方法？",
          "slug": "http有哪些方法？"
        },
        {
          "level": 2,
          "title": "这些方法的具体作用是什么？",
          "slug": "这些方法的具体作用是什么？"
        },
        {
          "level": 2,
          "title": "GET和POST有什么区别？",
          "slug": "get和post有什么区别？"
        },
        {
          "level": 2,
          "title": "PUT和POST都是给服务器发送新增资源，有什么区别？",
          "slug": "put和post都是给服务器发送新增资源，有什么区别？"
        },
        {
          "level": 2,
          "title": "PUT和PATCH都是给服务器发送修改资源，有什么区别？",
          "slug": "put和patch都是给服务器发送修改资源，有什么区别？"
        },
        {
          "level": 2,
          "title": "http的请求报文是什么样的？",
          "slug": "http的请求报文是什么样的？"
        },
        {
          "level": 2,
          "title": "http的响应报文是什么样的？",
          "slug": "http的响应报文是什么样的？"
        },
        {
          "level": 2,
          "title": "聊一聊HTTP的部首有哪些？",
          "slug": "聊一聊http的部首有哪些？"
        },
        {
          "level": 2,
          "title": "聊一聊HTTP的状态码有哪些？",
          "slug": "聊一聊http的状态码有哪些？"
        },
        {
          "level": 2,
          "title": "同样是重定向307，303，302的区别？",
          "slug": "同样是重定向307，303，302的区别？"
        },
        {
          "level": 2,
          "title": "HTTP的keep-alive是干什么的？",
          "slug": "http的keep-alive是干什么的？"
        },
        {
          "level": 2,
          "title": "为什么有了HTTP为什么还要HTTPS？",
          "slug": "为什么有了http为什么还要https？"
        },
        {
          "level": 2,
          "title": "HTTPS是如何保证安全的？",
          "slug": "https是如何保证安全的？"
        },
        {
          "level": 2,
          "title": "HTTP2相对于HTTP1.x有什么优势和特点？",
          "slug": "http2相对于http1-x有什么优势和特点？"
        },
        {
          "level": 3,
          "title": "二进制分帧",
          "slug": "二进制分帧"
        },
        {
          "level": 3,
          "title": "头部压缩",
          "slug": "头部压缩"
        },
        {
          "level": 3,
          "title": "服务器推送",
          "slug": "服务器推送"
        },
        {
          "level": 3,
          "title": "多路复用",
          "slug": "多路复用"
        },
        {
          "level": 2,
          "title": "HTTP的缓存的过程是怎样的？",
          "slug": "http的缓存的过程是怎样的？"
        },
        {
          "level": 2,
          "title": "什么时候会触发强缓存或者协商缓存？",
          "slug": "什么时候会触发强缓存或者协商缓存？"
        },
        {
          "level": 3,
          "title": "强缓存",
          "slug": "强缓存"
        },
        {
          "level": 3,
          "title": "协商缓存",
          "slug": "协商缓存"
        }
      ]
    },
    {
      "title": "HTTP笔试部分",
      "frontmatter": {},
      "regularPath": "/guide/httpWritten.html",
      "relativePath": "guide/httpWritten.md",
      "key": "v-67c1f0fa",
      "path": "/guide/httpWritten.html",
      "headers": [
        {
          "level": 2,
          "title": "缓存题",
          "slug": "缓存题"
        },
        {
          "level": 3,
          "title": "问题一：当点击“重新访问 page 页”链接重新加载该页面后， head.png 如何二次加载？",
          "slug": "问题一：当点击“重新访问-page-页”链接重新加载该页面后，-head-png-如何二次加载？"
        },
        {
          "level": 3,
          "title": "问题二：如果将上述信息中的 Cache-Control 设置为 private，那么结果又会如何呢？",
          "slug": "问题二：如果将上述信息中的-cache-control-设置为-private，那么结果又会如何呢？"
        }
      ]
    },
    {
      "title": "实现不可变数据",
      "frontmatter": {},
      "regularPath": "/guide/immutable.html",
      "relativePath": "guide/immutable.md",
      "key": "v-0b1c6be3",
      "path": "/guide/immutable.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 3,
          "title": "文章目录",
          "slug": "文章目录"
        },
        {
          "level": 3,
          "title": "1.可变数据的副作用",
          "slug": "_1-可变数据的副作用"
        },
        {
          "level": 3,
          "title": "2.不可变数据的解决方案",
          "slug": "_2-不可变数据的解决方案"
        },
        {
          "level": 3,
          "title": "3.实现更简单的immutable",
          "slug": "_3-实现更简单的immutable"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "JavaScript基础",
      "frontmatter": {},
      "regularPath": "/guide/jsBasic.html",
      "relativePath": "guide/jsBasic.md",
      "key": "v-1588a7c3",
      "path": "/guide/jsBasic.html",
      "headers": [
        {
          "level": 2,
          "title": "本章索引",
          "slug": "本章索引"
        },
        {
          "level": 2,
          "title": "解释下变量提升？✨",
          "slug": "解释下变量提升？✨"
        },
        {
          "level": 2,
          "title": "一段JavaScript代码是如何执行的？✨",
          "slug": "一段javascript代码是如何执行的？✨"
        },
        {
          "level": 2,
          "title": "理解闭包吗？✨",
          "slug": "理解闭包吗？✨"
        },
        {
          "level": 3,
          "title": "闭包是什么",
          "slug": "闭包是什么"
        },
        {
          "level": 3,
          "title": "闭包的作用",
          "slug": "闭包的作用"
        },
        {
          "level": 2,
          "title": "JavaScript的作用域链理解吗？✨",
          "slug": "javascript的作用域链理解吗？✨"
        },
        {
          "level": 2,
          "title": "谈谈你对原型链的理解？✨",
          "slug": "谈谈你对原型链的理解？✨"
        },
        {
          "level": 3,
          "title": "原型对象",
          "slug": "原型对象"
        },
        {
          "level": 3,
          "title": "原型链",
          "slug": "原型链"
        },
        {
          "level": 2,
          "title": "JavaScript有哪些类型？✨",
          "slug": "javascript有哪些类型？✨"
        },
        {
          "level": 2,
          "title": "如何判断是否是数组？",
          "slug": "如何判断是否是数组？"
        },
        {
          "level": 2,
          "title": "谈一谈你对this的了解？✨",
          "slug": "谈一谈你对this的了解？✨"
        },
        {
          "level": 2,
          "title": "那么箭头函数的this指向哪里？✨",
          "slug": "那么箭头函数的this指向哪里？✨"
        },
        {
          "level": 2,
          "title": "async/await是什么？",
          "slug": "async-await是什么？"
        },
        {
          "level": 2,
          "title": "async/await相比于Promise的优势？",
          "slug": "async-await相比于promise的优势？"
        },
        {
          "level": 2,
          "title": "JavaScript的参数是按照什么方式传递的？",
          "slug": "javascript的参数是按照什么方式传递的？"
        },
        {
          "level": 3,
          "title": "基本类型传递方式",
          "slug": "基本类型传递方式"
        },
        {
          "level": 3,
          "title": "复杂类型按引用传递?",
          "slug": "复杂类型按引用传递"
        },
        {
          "level": 3,
          "title": "按共享传递",
          "slug": "按共享传递"
        },
        {
          "level": 2,
          "title": "聊一聊如何在JavaScript中实现不可变对象？",
          "slug": "聊一聊如何在javascript中实现不可变对象？"
        },
        {
          "level": 2,
          "title": "JavaScript的基本类型和复杂类型是储存在哪里的？",
          "slug": "javascript的基本类型和复杂类型是储存在哪里的？"
        },
        {
          "level": 2,
          "title": "讲讲JavaScript垃圾回收是怎么做的？",
          "slug": "讲讲javascript垃圾回收是怎么做的？"
        }
      ]
    },
    {
      "title": "JavaScript笔试部分",
      "frontmatter": {},
      "regularPath": "/guide/jsWritten.html",
      "relativePath": "guide/jsWritten.md",
      "key": "v-2366ef63",
      "path": "/guide/jsWritten.html",
      "headers": [
        {
          "level": 2,
          "title": "实现防抖函数（debounce）",
          "slug": "实现防抖函数（debounce）"
        },
        {
          "level": 2,
          "title": "实现节流函数（throttle）",
          "slug": "实现节流函数（throttle）"
        },
        {
          "level": 2,
          "title": "深克隆（deepclone）",
          "slug": "深克隆（deepclone）"
        },
        {
          "level": 2,
          "title": "实现Event(event bus)",
          "slug": "实现event-event-bus"
        },
        {
          "level": 2,
          "title": "实现instanceOf",
          "slug": "实现instanceof"
        },
        {
          "level": 2,
          "title": "模拟new",
          "slug": "模拟new"
        },
        {
          "level": 2,
          "title": "实现一个call",
          "slug": "实现一个call"
        },
        {
          "level": 2,
          "title": "实现apply方法",
          "slug": "实现apply方法"
        },
        {
          "level": 2,
          "title": "实现bind",
          "slug": "实现bind"
        },
        {
          "level": 2,
          "title": "模拟Object.create",
          "slug": "模拟object-create"
        },
        {
          "level": 2,
          "title": "实现类的继承",
          "slug": "实现类的继承"
        },
        {
          "level": 2,
          "title": "实现JSON.parse",
          "slug": "实现json-parse"
        },
        {
          "level": 2,
          "title": "实现Promise",
          "slug": "实现promise"
        }
      ]
    },
    {
      "title": "JavaScript的运行机制",
      "frontmatter": {},
      "regularPath": "/guide/mechanism.html",
      "relativePath": "guide/mechanism.md",
      "key": "v-772cb57a",
      "path": "/guide/mechanism.html",
      "headers": [
        {
          "level": 2,
          "title": "JavaScript的执行环境",
          "slug": "javascript的执行环境"
        },
        {
          "level": 3,
          "title": "JavaScript引擎(JavaScript Engine)",
          "slug": "javascript引擎-javascript-engine"
        },
        {
          "level": 3,
          "title": "JavaScript运行时（JavaScript Runtime）",
          "slug": "javascript运行时（javascript-runtime）"
        },
        {
          "level": 3,
          "title": "可执行代码",
          "slug": "可执行代码"
        },
        {
          "level": 2,
          "title": "JavaScript执行",
          "slug": "javascript执行"
        },
        {
          "level": 3,
          "title": "堆",
          "slug": "堆"
        },
        {
          "level": 3,
          "title": "调用栈",
          "slug": "调用栈"
        },
        {
          "level": 3,
          "title": "执行上下文(execution context)",
          "slug": "执行上下文-execution-context"
        },
        {
          "level": 3,
          "title": "执行过程",
          "slug": "执行过程"
        },
        {
          "level": 2,
          "title": "小结",
          "slug": "小结"
        },
        {
          "level": 3,
          "title": "this是怎么被绑定的?",
          "slug": "this是怎么被绑定的"
        },
        {
          "level": 3,
          "title": "作用域链是怎么形成的？",
          "slug": "作用域链是怎么形成的？"
        },
        {
          "level": 3,
          "title": "闭包是怎么形成的？",
          "slug": "闭包是怎么形成的？"
        }
      ]
    },
    {
      "title": "JavaScript内存管理",
      "frontmatter": {},
      "regularPath": "/guide/memory.html",
      "relativePath": "guide/memory.md",
      "key": "v-5a9e26c7",
      "path": "/guide/memory.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "内存模型",
          "slug": "内存模型"
        },
        {
          "level": 2,
          "title": "生命周期",
          "slug": "生命周期"
        },
        {
          "level": 2,
          "title": "内存回收",
          "slug": "内存回收"
        },
        {
          "level": 3,
          "title": "V8的内存分代",
          "slug": "v8的内存分代"
        },
        {
          "level": 3,
          "title": "Stop The World （全停顿）",
          "slug": "stop-the-world-（全停顿）"
        },
        {
          "level": 3,
          "title": "Scavenge 算法",
          "slug": "scavenge-算法"
        },
        {
          "level": 3,
          "title": "对象晋升",
          "slug": "对象晋升"
        },
        {
          "level": 3,
          "title": "Mark-Sweep & Mark-Compact",
          "slug": "mark-sweep-mark-compact"
        },
        {
          "level": 3,
          "title": "Incremental Marking（增量标记）",
          "slug": "incremental-marking（增量标记）"
        },
        {
          "level": 3,
          "title": "lazy sweeping（延迟清理）",
          "slug": "lazy-sweeping（延迟清理）"
        },
        {
          "level": 2,
          "title": "内存泄露",
          "slug": "内存泄露"
        },
        {
          "level": 3,
          "title": "引起内存泄漏的几个禁忌",
          "slug": "引起内存泄漏的几个禁忌"
        },
        {
          "level": 3,
          "title": "查看内存泄漏",
          "slug": "查看内存泄漏"
        }
      ]
    },
    {
      "title": "为什么会有这个项目",
      "frontmatter": {},
      "regularPath": "/guide/preface.html",
      "relativePath": "guide/preface.md",
      "key": "v-8c976b3a",
      "path": "/guide/preface.html",
      "headers": [
        {
          "level": 2,
          "title": "大量的过时问题",
          "slug": "大量的过时问题"
        },
        {
          "level": 2,
          "title": "深入浅出的不多",
          "slug": "深入浅出的不多"
        },
        {
          "level": 2,
          "title": "缺乏基础知识",
          "slug": "缺乏基础知识"
        },
        {
          "level": 2,
          "title": "方向不够全面",
          "slug": "方向不够全面"
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "xiaomuzhu/front-end-interview",
    "editLinks": true,
    "docsDir": "packages/docs/docs",
    "locales": {
      "/": {
        "editLinkText": "在 GitHub 上编辑此页",
        "nav": [
          {
            "text": "指南",
            "link": "/guide/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "前言",
              "collapsable": false,
              "children": [
                "",
                "preface"
              ]
            },
            {
              "title": "推荐",
              "collapsable": false,
              "children": [
                "book"
              ]
            },
            {
              "title": "前端基础",
              "collapsable": false,
              "children": [
                "htmlBasic",
                "cssBasic",
                "jsBasic",
                "http",
                "browser",
                "dom"
              ]
            },
            {
              "title": "前端基础笔试",
              "collapsable": false,
              "children": [
                "httpWritten",
                "jsWritten"
              ]
            },
            {
              "title": "前端原理详解",
              "collapsable": false,
              "children": [
                "hoisting",
                "mechanism",
                "eventLoop",
                "immutable",
                "memory",
                "deepclone",
                "event"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "前端面试与进阶指南",
      "description": "可能是全网最给力的前端面试项目",
      "path": "/"
    }
  }
}